### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by Perrin-the-wolf** [Flomp/wanderer#116]
Hello,
I have installed the tool. Unfortunately, I first created some weeks ago a user and didn't remember the password, as I have now time to dive deeper into the platform. Now I can't find a way to reset it, only to create new users. A password reset would be useful.
Kind regards

**Comment by tofublock** [comment]
You can do that in the backend. See [Backend access](https://wanderer.to/guides/custom-categories/).

**Comment by Perrin-the-wolf** [comment]
Thanks, didn't know this part of the backend. I only looked at the settingsmenu in Wanderer

**Comment by Flomp** [comment]
However, I think that there still should be an option for a user without backend access to reset his password. I implemented this feature for the next patch. The platform admin of the wanderer instance will need to setup a SMTP connection in PocketBase so that the password reset emails can be sent properly.
