### ISSUE TITLE
[Feature Request] Additional Categories

### ISSUE THREAD

**Issue by reisschuessel** [Flomp/wanderer#78]
Hi,

thanks for the great work! 

Would it be possible to add additional Categories besides "Walking", "Hiking" etc?
Or add the possibility to add them via some setting in the UI?

I am thinking about "Driving" or "Biking" because i also track interesting drives by car and would find it very useful to categorize them as such.

Thanks,
Niels

**Comment by tuhriel** [comment]
I support that, would be really cool if the categories could be adapted by the user. I'm thinking about using it to track my motorbike and routes and maybe some gpx tracks for foto tours, so most of the pre-existing routes aren't relevant.

**Comment by Flomp** [comment]
Hey,

Thanks for your request. Categories are currently already dynamic, but they need to be edited in the backend. You can do so by accessing your PocketBase instance's admin panel (default is `http://localhost:8090/_/`) and creating a new admin user. Then you can create, update and delete entries in the `categories` table that will be reflected in the frontend.

I agree that this is currently a bit cumbersome. Adding this option to the frontend would mean that I would need users with different levels of authorization. This feels a bit like reinventing the wheel because PocketBase already comes with the option to create admin users.

**Comment by tuhriel** [comment]
@Flomp: thanks for the info. Worked like a charm. Might be a good idea to add this to the Wiki. If it's ok with you I could create a PR with an updated dok (probably under https://github.com/Flomp/wanderer/wiki/Configuration#pocketbase)

**Comment by Flomp** [comment]
Glad, it worked. The wiki is deprecated (I should probably delete it soon). If you'd like to submit a pull request, please do so for the docs: https://github.com/Flomp/wanderer/tree/main/docs/src/content/docs

Thanks!

**Comment by reisschuessel** [comment]
@Flomp: thank you for explaining how to do it. It worked and i am happy!

**Comment by Flomp** [comment]
Great! I'll close this for now then.
