### ISSUE TITLE
Remember the sort field and direction in the Trails page

### ISSUE THREAD

**Issue by bevalentin** [Flomp/wanderer#79]
Hi,

The Trails page does not remember the last selected sort field and direction: they are reset to increasing Creation Date each time we come back to the page. This works fine with the Cards / List display option, however.

It would be nice to remember the sort field and direction too.

Other minor stuff: the `fa-person-hiking` icon is always used to display the trail difficulty, whatever the selected trail category.

Thanks for this great application!

Bernard

**Comment by Flomp** [comment]
This is now implemented in v0.7.0.

**Comment by PaddyPat** [comment]
Short comment for sorting tracks:

If you have many and several pages of tracks (1500 Tracks), it sorts every page only so on page 1 ist date descenting 31.03.2024-01.03.2024. page 2 shows 31.04.2024-01.04.2024 and so on so it splits the sorting on every page and not via all tracks.

For me I would like to sort by date descending, because I like to see the latest track at the top and than the oldes track on page 204 ;.) .

**Comment by Flomp** [comment]
@PaddyPat thanks for pointing that out. I published a fix in v0.7.1.
